name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if you use another branch for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v1

      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v1